### ISSUE TITLE
crossValidate doesn't recognise verbose argument

### ISSUE THREAD

**Issue by wlason** [DarioS/ClassifyR#101]
Thanks for the great package!

I noted that `crossValidate` doesn't recognise the `verbose` argument. This is the error it produces:
`Error in .local(measurements, outcome, ...) : 
  unused argument (verbose = 1)`
Same with any other level (2 or 3).

**Comment by DarioS** [comment]
Ah, I see the problem. `crossValidate` accepts `verbose` for the `DataFrame` S4 method but not for `matrix`, `data.frame` nor `MultiAssayExperiment` varieties. My colleague who wrote the `crossValidate` wrappers for each input data type isn't fond of `...` which is what `runTests` uses to pass `verbose` onwards. All S4 methods convert input data and funnel into the `DataFrame` one which does all of the work. Thanks for letting me know and it will be fixed soon.
