### ISSUE TITLE
AUC performance metric in crissCrossValidate

### ISSUE THREAD

**Issue by Harry25R** [DarioS/ClassifyR#109]
Hi team, 

Just noticed that the AUC performance metric seems to break when using crissCrossValidate. Just curious if you can take a look at this.

**Comment by DarioS** [comment]
Ah, `crissCrossValidate` was removing prediction probabilities and only keeping the predicted `factor` labels.
```r
if(is(predictions, "tabular"))
  predictions <- predictions[, match(c("class", "risk"), colnames(predictions))]
```
It has been fixed in RELEASE_3_20 and devel branches.
