### ISSUE TITLE
Model Comparison Feature

### ISSUE THREAD

**Issue by ecool50** [DarioS/ClassifyR#74]
Hi,
Would it be possible to have a feature in ClassifyR that runs many models and ranks their results based on a specified metric such as `AUC` or `Balanced Accuracy`? This would be extremely useful for those wanting to compare different models without having to run them each individually. This is similar to the AutoML feature in the `H2o` package. I've included an example of its output below.

![image](https://user-images.githubusercontent.com/8261982/227813055-641bd631-89a1-41b6-ac17-1f886bfa0f02.png)

**Comment by DarioS** [comment]
There is already `crossValidate` for building many models. A function which creates a performance summary table is needed.

**Comment by DarioS** [comment]
Implemented as `performanceTable`.
