### ISSUE TITLE
No vignette/examples for survival analysis

### ISSUE THREAD

**Issue by adam2o1o** [DarioS/ClassifyR#87]
Hi there, I'd like to use ClassifyR for survival analysis but there arent any examples I can find. If you could help that would be great, thanks

**Comment by DarioS** [comment]
The package is near the time limit for Bioconductor checking but I think I can squeeze in some. Perhaps using [MetaGxBreast](https://bioconductor.org/packages/release/data/experiment/html/MetaGxBreast.html). But it's basically just specifying the `outcome` in a couple of different ways, as mentioned in Quick Start section.

> `crossValidate` must also be supplied with `outcome`, which represents the prediction to be made in a variety of ways.
>
> - A `factor` that contains the class label for each observation. classes must be of length _n_.
> - A `character` of length 1 that matches a column name in a data frame which holds the classes. The classes will automatically be removed before training is done.
> - **A `Surv` object of the same length as the number of samples in the data which contains information about the time and censoring of the samples.**
> - **A `character` vector of length 2 or 3 that each match a column name in a data frame which holds information about the time and censoring of the samples. The time-to-event columns will automatically be removed before training is done.**

**Comment by nick-robo** [comment]
Maybe you could set `eval=FALSE` for some heavier operations or examples. Only `BiocCheck` complains about this and it is not run on the package after release.

**Comment by DarioS** [comment]
[Article showing survival analysis of METABRIC breast cancer clinical data](https://sydneybiox.github.io/ClassifyR/articles/survival.html) added. Please close if sufficient or suggest changes.
