### ISSUE TITLE
Cross validate doesn't match up assay row names to names of outcome vector.

### ISSUE THREAD

**Issue by fame2827** [DarioS/ClassifyR#88]
Hello, I've noticed if the rownames of the assay are not ordered the same as the names in the outcome vector, then ClassifyR will classify samples with the wrong outcome. This is particularly prominent when numeric row names are of type character where the ordering might be "1", "10", "2", "3", rather than 1, 2, 3, 10.

**Comment by DarioS** [comment]
Ah, the assumption is that they are all sorted in same order. It seems to have dropped out of the documentation at some stage. To make it more robust, though, I have now put in safety if names are on both covariates and outcomes. For instance:

```r
# Names are on both the covariates and outcome. Ensure consistent ordering.
if(!is.null(rownames(measurements)) && !is.null(names(outcome)))
  measurements <- measurements[match(names(outcome), rownames(measurements)), ]
```

**Comment by fame2827** [comment]
Awesome, thanks!
