### ISSUE TITLE
Train function doesn't allow selectionMethod = "none" with coxNet.

### ISSUE THREAD

**Issue by fame2827** [DarioS/ClassifyR#90]
Running these lines of code spits out the following error: 
`Error in .doSelection(measurementsUse, outcomeTrain, CrossValParams(), :  trying to get slot "tuneParams" from an object of a basic class ("NULL") with no slots`

```
classifier = "CoxNet"
selectionMethod = "none"

output = train(
  x = DataFrame(measurements),
  outcome = outcome,
  classifier = classifier,
  selectionMethod  = selectionMethod,
)
```

**Comment by DarioS** [comment]
Oh, yeah, I need check `if(!is.null(modellingParams@selectParams))` for no separate selection. Committed to both repositories.
