### ISSUE TITLE
Class list for CoxNet models, affecting the predict function.

### ISSUE THREAD

**Issue by fame2827** [DarioS/ClassifyR#91]
When training a coxNet model using using the classifyR train function. The resulting model has the following class `"trainedByClassifyR", "coxnet", "glmnet" `. However when predicting using this model with the predict function I get the following error `Error in h(simpleError(msg, call)) :  error in evaluating the argument 'x' in selecting a method for function 't': 'data' must be of a vector type, was 'NULL'`.

Removing "glmnet" from the class list seems to solve this issue. As shown below:

```
output = train(
  x = DataFrame(measurements),
  outcome = outcome,
  classifier = "CoxNet",
  selectionMethod  = "CoxPH",
  nFeatures = 15
)

class(output) = class(output)[1:2]

predict(output, measurements)
```

**Comment by DarioS** [comment]
A problem and its solution! Fixed by my latest commit.
